#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "No specified bucket name."
    exit -1
fi


if [ -z "$2" ]; then
    echo "No specified file to upload."
    exit -1
fi

BUCKET_NAME=$1
UPLOAD_FILE_PATH=$2
OBJECT_KEY=$(basename "$2")


aws s3api put-object \
--bucket $BUCKET_NAME \
--key $OBJECT_KEY \
--body $UPLOAD_FILE_PATH

echo "File $UPLOAD_FILE_PATH is successfully uploaded to $BUCKET_NAME."