#!/usr/bin/env bash

LOCAL_DIR='./tmp'

# Check if the argument is a valid directory
if [ ! -d "$1" ]; then
    echo "The provided path is not a directory."
    exit 1
fi

LOCAL_DIR=$1

if [ -z "$2" ]; then
    echo "No specified S3 Bucket URI"
    exit -1
fi

S3_BUCKET="s3://$2"

# Sync the local directory to the S3 bucket
echo "Syncing $LOCAL_DIR to $S3_BUCKET..."
aws s3 sync "$LOCAL_DIR" "$S3_BUCKET"

# Check if the sync was successful
if [ $? -eq 0 ]; then
    echo "Sync completed successfully."
else
    echo "Error occurred during sync."
    exit 1
fi
